# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PolenApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PolenApp
  pod 'SwiftLint'

  target 'PolenAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PolenAppUITests' do
    # Pods for testing
  end

end
